language: php
sudo: false

php:
  - 5.5
  - 5.6

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - mongodb-org-server
      - mongodb-org-shell
    sources:
      - mongodb-upstart

before_install:
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - composer config -g github-oauth.github.com $CI_USER_TOKEN
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - mongo admin --eval "db.createUser({user:'root', pwd:'root', roles:[]})"

install:
  - export SYMFONY_ENV=test
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_ACCESS_TOKEN" --format=php-clover build/logs/clover.xml
