parameters:
    itkg_reference.transformer.reference.class                : Itkg\ReferenceApiBundle\Transformer\ReferenceTransformer
    itkg_reference.transformer.reference_collection.class     : Itkg\ReferenceApiBundle\Transformer\ReferenceCollectionTransformer
    itkg_reference.transformer.reference_type.class           : Itkg\ReferenceApiBundle\Transformer\ReferenceTypeTransformer
    itkg_reference.transformer.reference_type_collection.class: Itkg\ReferenceApiBundle\Transformer\ReferenceTypeCollectionTransformer

services:
    itkg_reference.transformer.reference:
        class: '%itkg_reference.transformer.reference.class%'
        tags :
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_collection:
        class: '%itkg_reference.transformer.reference_collection.class%'
        tags :
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_type:
        class    : '%itkg_reference.transformer.reference_type.class%'
        arguments:
            - '%itkg_reference.facade.reference_type.class%'
            - '@open_orchestra_backoffice.manager.multi_languages_choice'
            - '@itkg_reference.repository.reference'
            - '@itkg_reference.repository.reference_type'
            - '@security.authorization_checker'
        tags     :
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_type_collection:
        class    : '%itkg_reference.transformer.reference_type_collection.class%'
        arguments:
            - '%itkg_reference.facade.reference_type_collection.class%'
        tags     :
            - { name: open_orchestra_api.transformer.strategy}
