Itkg\ReferenceModelBundle\Document\Reference:
    properties:
        name:
            - NotBlank: ~
        referenceType:
            - NotBlank: ~
        language:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        attributes:
            - Valid: ~
