parameters:
    itkg_reference.manager.reference_type.class : Itkg\ReferenceBundle\Manager\ReferenceTypeManager
    itkg_reference.manager.reference.class      : Itkg\ReferenceBundle\Manager\ReferenceManager

services:
    itkg_reference.manager.reference_type:
        class   : '%itkg_reference.manager.reference_type.class%'
        arguments:
          - '%itkg_reference.document.reference_type.class%'

    itkg_reference.manager.reference:
        class    : '%itkg_reference.manager.reference.class%'
        arguments:
          - '@open_orchestra_backoffice.context_manager'
